export const CHANGE_STOCK_SYMBOL = 'CHANGE_STOCK_SYMBOL';
export const CHANGE_FROM_DATE = 'CHANGE_FROM_DATE';
export const CHANGE_TO_DATE = 'CHANGE_TO_DATE';
export const CHANGE_SOCIAL_MEDIA = 'CHANGE_SOCIAL_MEDIA';
export const FETCH_STOCK_INFO = 'FETCH_STOCK_INFO';
export const STOCK_INFO_FETCHED = 'STOCK_INFO_FETCHED';
